package io.github.recrafter.lapis.phases.generator

import io.github.recrafter.lapis.Lapis

object GeneratorConstants {
    const val GENERATED_HEADER: String = "Generated by ${Lapis.NAME}. Do not edit!"
    val INDENT: String = " ".repeat(4)
}
