package io.github.recrafter.lapis.extensions.jp

import io.github.recrafter.lapis.LapisMeta
import io.github.recrafter.lapis.layers.generator.builders.IrJavaCodeBlockBuilder
import io.github.recrafter.lapis.layers.lowering.types.IrClassName
import io.github.recrafter.lapis.layers.lowering.types.IrTypeName

typealias JPCodeBlockBuilder = com.palantir.javapoet.CodeBlock.Builder
typealias JPCodeBlock = com.palantir.javapoet.CodeBlock

typealias JPAnnotationBuilder = com.palantir.javapoet.AnnotationSpec.Builder
typealias JPAnnotation = com.palantir.javapoet.AnnotationSpec

typealias JPFieldBuilder = com.palantir.javapoet.FieldSpec.Builder
typealias JPField = com.palantir.javapoet.FieldSpec

typealias JPMethodBuilder = com.palantir.javapoet.MethodSpec.Builder
typealias JPMethod = com.palantir.javapoet.MethodSpec

typealias JPParameterBuilder = com.palantir.javapoet.ParameterSpec.Builder
typealias JPParameter = com.palantir.javapoet.ParameterSpec

typealias JPClassBuilder = com.palantir.javapoet.TypeSpec.Builder
typealias JPClass = com.palantir.javapoet.TypeSpec

typealias JPFile = com.palantir.javapoet.JavaFile

typealias JPType = com.palantir.javapoet.TypeName
typealias JPClassType = com.palantir.javapoet.ClassName
typealias JPGenericType = com.palantir.javapoet.ParameterizedTypeName
typealias JPWildcardType = com.palantir.javapoet.WildcardTypeName
typealias JPVariableType = com.palantir.javapoet.TypeVariableName
typealias JPArrayType = com.palantir.javapoet.ArrayTypeName

typealias JPModifier = javax.lang.model.element.Modifier

val JPVoid: JPType = JPType.VOID
val JPBoolean: JPType = JPType.BOOLEAN
val JPByte: JPType = JPType.BYTE
val JPShort: JPType = JPType.SHORT
val JPInt: JPType = JPType.INT
val JPLong: JPType = JPType.LONG
val JPChar: JPType = JPType.CHAR
val JPFloat: JPType = JPType.FLOAT
val JPDouble: JPType = JPType.DOUBLE

val JPObject: JPClassType = JPClassType.OBJECT
val JPString: JPClassType = JPClassType.get(String::class.java)
val JPList: JPClassType = JPClassType.get(List::class.java)
val JPSet: JPClassType = JPClassType.get(Set::class.java)
val JPMap: JPClassType = JPClassType.get(Map::class.java)

val JPStar: JPWildcardType = JPWildcardType.subtypeOf(JPObject)

inline fun <reified A : Annotation> buildJavaAnnotation(builder: JPAnnotationBuilder.() -> Unit = {}): JPAnnotation =
    JPAnnotation.builder(JPClassType.get(A::class.java)).apply(builder).build()

fun buildJavaCodeBlock(builder: IrJavaCodeBlockBuilder.() -> Unit = {}): JPCodeBlock =
    IrJavaCodeBlockBuilder(JPCodeBlock.builder()).apply(builder).build()

fun buildJavaCodeBlock(
    format: String,
    arguments: IrJavaCodeBlockBuilder.Arguments.() -> Unit = {}
): JPCodeBlock =
    buildJavaCodeBlock {
        add(format, arguments)
    }

fun buildJavaField(name: String, typeName: IrTypeName, builder: JPFieldBuilder.() -> Unit = {}): JPField =
    JPField.builder(typeName.java, name).apply(builder).build()

fun buildJavaMethod(name: String, builder: JPMethodBuilder.() -> Unit = {}): JPMethod =
    JPMethod.methodBuilder(name).apply(builder).build()

fun buildJavaParameter(name: String, typeName: IrTypeName, builder: JPParameterBuilder.() -> Unit = {}): JPParameter =
    JPParameter.builder(typeName.java, name).apply(builder).build()

fun buildJavaInterface(name: String, builder: JPClassBuilder.() -> Unit = {}): JPClass =
    JPClass.interfaceBuilder(name).apply(builder).build()

fun buildJavaClass(name: String, builder: JPClassBuilder.() -> Unit = {}): JPClass =
    JPClass.classBuilder(name).apply(builder).build()

fun buildJavaFile(className: IrClassName, builder: () -> JPClass): JPFile =
    JPFile
        .builder(className.packageName, builder())
        .addFileComment("Generated by ${LapisMeta.NAME}. Do not edit!")
        .indent(" ".repeat(4))
        .build()
